### ISSUE TITLE
Regarding installation of chemie-turk

### ISSUE THREAD

**Issue by sreekanth221998** [asibanez/chemie-turk#1]
I'm unable to resolve the attached issue. Could you please me to resolve thsis
![Screenshot (25)](https://user-images.githubusercontent.com/98341841/154240233-89097bdd-8fa7-4606-91ff-04ddb5c42bf6.png)

**Comment by edgarsmdn** [comment]
Hi @sreekanth221998, take a look at the Pull request #2 that I submit for some extra details for installing and running `chemie-turk`

**Comment by sreekanth221998** [comment]
Thankyou very much @edgarsmdn for your clear explanation . It helped me and it's working
